### ISSUE TITLE
OO api with eieio?

### ISSUE THREAD

**Issue by Silex** [Silex/docker-api.el#2]
Do we want to make some kind of OO api?

For example:

``` elisp
(let ((images (docker-images))
      (first-image (car images)))
  (docker-image-pull first-image)
  (docker-image-push first-image "Foo:bar")
  (docker-image-rmi first-image))
```

With `eieio` methods for each api (pull/push/etc).

Inspiration: https://github.com/swipely/docker-api

**Comment by tzz** [comment]
@Silex since you could be dealing with multiple daemons across multiple machines, maybe something like this would make sense:

```
(with-docker-daemon mydaemon
  (docker-image-pull ...))
```

Without the `with-docker-daemon` wrapper, all the operations then implicitly work on the local Docker daemon, as users would expect.

It's unclear what happens if you take an image from one daemon and hand it to another. Maybe across daemons, the image is serialized as just a string... and other things are just not portable, like running processes, but could again be serialized to strings.

**Comment by Silex** [comment]
@tzz: hum, I don't think many people would want to talk to different docker daemon at the same time... but anyway, here's what you can do for now:

``` elisp
(docker-image-rm id)) ;; delete image locally
(let ((docker-api-host-url "tcp://11.22.33.44:12345"))
  (docker-image-rm id)) ;; delete image remotely
```

**Comment by Silex** [comment]
@tzz: same here, this issue was solved by using `json.el`... I'll open a new issue for your idea
